spring.application.name=MicroservicioCarrera
# Configuración del servidor
server.port=8080

# Configuración de conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/root  # Cambia "root" si usas un nombre de base de datos diferente
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

