spring.application.name=microservice-carrera
# Configuración del servidor
server.port=9090

# Configuración de conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/carreras_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.config.import=optional:configserver:http://localhost:8888

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest