spring.application.name=microservice-eureka

spring.config.import: optional:configserver:http://localhost:8888

# Configura el registro en Eureka
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false